name: pointsoup
channels:
  - pytorch3d
  - pytorch
  - fvcore
  - iopath
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pip
  - matplotlib==3.8.3
  - pandas==2.2.1
  - pytorch==2.0.1
  - torchvision==0.15.2
  - torchaudio==2.0.2
  - fvcore
  - iopath
  - plyfile==1.0.3
  - pyntcloud==0.3.1
  - ninja
  - pip:
      - torchac==0.9.3
      - contourpy==1.2.0
      - cycler==0.12.1
      - fonttools==4.50.0
      - kiwisolver==1.4.5
      - packaging==24.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - scipy==1.12.0
      - six==1.16.0
      - tzdata==2024.1
      - pandas==2.2.1
      - open3d==0.18.0
      # PyTorch3D build from source for CPU/MPS
      - git+https://github.com/facebookresearch/pytorch3d.git

